#! /usr/bin/env python3

# provided by a student in class discord server 

import sys


if len(sys.argv) != 2:
    print("SYNTAX: %s <filename>" % sys.argv[0], file=sys.stderr)
    sys.exit(1)

count = 0

for line in open(sys.argv[1], "rb"):
    line = line.decode("windows-1252")
    line = line.split('#')[0].strip()
    if line != "":
        count += 1

print("%s\t%d" % (sys.argv[1],count))

